### ISSUE TITLE
Duplicate package

### ISSUE THREAD

**Issue by rejeep** [scottaj/mocha.el#21]
Hey,

Don't know if you are aware of this, but I started on a mocha.el mode for Emacs quite some time ago, but never finished (see https://github.com/rejeep/mocha.el). Seems like an awful waste that we work on our own package instead of collaborating.

I haven't worked with JS for quite some time, hence the reason for not finishing the mode, but I believe that's about to change, so a mocha mode would be awesome.

I propose we merge the projects. As you already have everything set up with Melpa, etc..., how about I add my stuff to your project? I don't know when I'll be working on that, but I'll let you know.

**Comment by scottaj** [comment]
That sounds great. Feel free to open any PRs to merge stuff in. 

Do you have a list of feature differences between you project and mine? That may be goo to throw into a checklist on here to track the progress of the integration.

**Comment by rejeep** [comment]
These are the main things I'm missing from this package (correct me if I'm wrong):

1. I would like there to be tests with Travis and all those nice things. It's really hard to contribute without it.
2. Support for Nvm. My mode has support and it's really simple. Also see https://github.com/rejeep/nvm.el
3. Support for CoffeeScript (js2-mode required)
4. Better opts-file handling. I work in projects where we have unit/acceptance/system/integration tests all running with different mocha options (different mocha opts-files). I would like the package to search upwards from the test-file until it finds a `mocha.opts` file and then use that.

**Comment by scottaj** [comment]
Sounds good

1 .I have #10 tracking adding tests, I've been wanting to do that but haven't had much time for OSS stuff lately.
2. Yes, I've been wanting to do that and there is issue #1 tracking that. 
3. I'm pretty sure this works fine with CoffeScript now, with the caveat that test-at-point doesn't work
4. That is fair, it doesn't do anything with opts files now. As a note, you can work around this (and I do now) by putting custom paths in a `.dir-locals.el`

How do you feel about making issues for each thing you want to bring in that doesn't already exist?

**Comment by rejeep** [comment]
Added two issues! 👍
