### ISSUE TITLE
Support CoffeeScript for test at point

### ISSUE THREAD

**Issue by rejeep** [scottaj/mocha.el#23]
Add support for CoffeeScript files for the function `mocha-test-at-point`. The current implementation depends on js2-mode, which is a JS mode only.

**Comment by scottaj** [comment]
I imagine this will have to be regex based like rspec mode for ruby, unless there is an external tool we can hook into to do AST parsing for CS.

**Comment by rejeep** [comment]
I think a regex is good enough, at least to start with.
