### ISSUE TITLE
`node` command not found

### ISSUE THREAD

**Issue by marc0s** [scottaj/mocha.el#35]
When customizing `mocha-which-node` to `$HOME/project/node_modules/.bin/babel-node` to be able to run ES6 tests, I got a `/usr/bin/env: ‘node’: No such file or directory` error when running `M-x mocha-test-file`.

I have no knowledge of how `compilation-start` works and if it's aware of current `PATH`, I'm just a few months only emacs user.  `compilation-start` is as far as I could get to debug this :)

If I run `M-x shell` I can run `/usr/bin/env node` without errors.

Thanks.

**Comment by scottaj** [comment]
Hi, what version of `babel-node` are you using, I'd like to set up a sample project (or maybe you can point me at yours if it is OSS) to try this out. 

It should not be a path issue because it is an absolute path.

**Comment by marc0s** [comment]
Hi, I'm using `babel@6.5.2`.  Unfortunately this is not an OSS project where I'm testing it, but I'm able to produce any debug output you might need.

Thanks!

**Comment by scottaj** [comment]
I know this is sidestepping the issue you are having, which I still want to look into tonight, but is there a reason you are not just using the `--compilers` flag for mocha to preprocess with babel?

**Comment by marc0s** [comment]
I didn't though of that `--compilers` flag, but I tried with `mocha --compilers js:babel-register tests/unit/core/Users.js` and tests didn't pass at all, didn't investigate, but running them with `gulp test` work fine (and it's just a `gulp.src` piped into `gulp-mocha`).

If I try `mocha-test-file` without any customization, the used `mocha` command is the one at `node_modules/.bin/mocha` which in turn is a symlink to `../mocha/bin/mocha` that has a shebang to `#!/usr/bin/env mocha` and it fails with the same error: `node node_modules/.bin/mocha --recursive --reporter dot /home/marcos/foo/tests/unit/core/Users.js
zsh:1: command not found: node`

Maybe I have something broken from the ground up and I'm not aware of...

Thanks!

**Comment by scottaj** [comment]
I'm closing this because it is not clear there is an issue with mocha.el. If you find that there is and have more specifics, please open another issue.
