### ISSUE TITLE
Fix error regexp to support Windows filenames

### ISSUE THREAD

**Issue by felipeochoa** [scottaj/mocha.el#39]
The regex taken from [Ben Hollis' blog](https://benhollis.net/blog/2015/12/20/nodejs-stack-traces-in-emacs-compilation-mode/)[1] is missing the windows path separator (backslash) from the set of allowed filename characters, so stack traces where the error is in a subdirectory don't link properly. Adding the backslash character to `node-error-regexp` fixes this issue:

``` diff
--- a/mocha.el
+++ b/mocha.el
@@ -57,7 +57,7 @@
 (defvar mocha-project-test-directory nil)

 (defvar node-error-regexp
-  "^[  ]+at \\(?:[^\(\n]+ \(\\)?\\([a-zA-Z\.0-9_/-]+\\):\\([0-9]+\\):\\([0-9]+\\)\)?$"
+  "^[  ]+at \\(?:[^\(\n]+ \(\\)?\\([a-zA-Z\.0-9_/-\\]+\\):\\([0-9]+\\):\\([0-9]+\\)\)?$"
   "Regular expression to match NodeJS errors.
 From http://benhollis.net/blog/2015/12/20/nodejs-stack-traces-in-emacs-compilation-mode/")

```

![no match](https://cloud.githubusercontent.com/assets/2739312/19378367/69ba521e-91ec-11e6-8f32-cb000872d574.png)

![matches](https://cloud.githubusercontent.com/assets/2739312/19378364/65e7b302-91ec-11e6-9291-4337a5d01346.png)

[1]: I've also emailed Ben about this

**Comment by scottaj** [comment]
This looks good to me, can you put your patch into a PR?
