### ISSUE TITLE
Support testing in modes derived from js2

### ISSUE THREAD

**Issue by felipeochoa** [scottaj/mocha.el#41]
`mocha-find-current-test` refuses to run unless the current major mode is exactly `js2`. This is inconvenient when using modes deriving from it, like `js2-jsx` or `rjsx` (forgive the plug 😄).

```elisp
(defun mocha-find-current-test ()
  "Try to find the innermost 'describe' or 'it' using js2-mode.

When a 'describe' or 'it' is found, return the first argument of that call.
If js2-mode is not enabled in the buffer, returns nil.
If there is no wrapping 'describe' or 'it' found, return nil."
  (if (string= major-mode "js2-mode")
      (let ((node (js2-node-at-point)))
        (mocha-walk-up-to-it node))
    (progn
      (message "js2-mode must be enabled to run test at point.")
      nil)))
```

Testing for a descendant mode is easy to do, so the whole thing can be fixed with:

```elisp
(defun mocha-mode-descends-from (major-mode ancenstor)
  "Return t if MAJOR-MODE is derived from ANCENSTOR, or nil otherwise."
  (or (eq major-mode ancenstor)
      (let ((parent (get major-mode 'derived-mode-parent)))
        (cond ((eq parent ancenstor) t)
              ((not (null parent)) (mocha-mode-descends-from parent ancenstor))
              (t nil)))))

(defun mocha-find-current-test ()
  "Try to find the innermost 'describe' or 'it' using js2-mode.

When a 'describe' or 'it' is found, return the first argument of that call.
If js2-mode is not enabled in the buffer, returns nil.
If there is no wrapping 'describe' or 'it' found, return nil."
  (if (mocha-mode-descends-from major-mode 'js2-mode)
      (let ((node (js2-node-at-point)))
        (mocha-walk-up-to-it node))
    (progn
      (message "js2-mode must be enabled to run test at point.")
      nil)))
```

**Comment by scottaj** [comment]
Looks solid, can you put this patch into a PR?

**Comment by felipeochoa** [comment]
I was starting to do this, and then wondered whether it wouldn't be better to just call `(js2-node-at-point)` directly without the mode check. If called in a buffer without a `js2` ast, `js2` (at least the latest version) errors with `js2-node-at-point: No JavaScript AST available`. 

If you want to keep the test, would you mind if I change the `message` to an `error`? I think it makes more sense since we need to halt anyway. That makes it easier to test this function

**Comment by scottaj** [comment]
That is actually a very reasonable error message, so I'm fine with it just failing on that. The docs call out that you need js2-mode so I don't think the explicit check is adding a ton of value.
