### ISSUE TITLE
Imenu support

### ISSUE THREAD

**Issue by DamienCassou** [scottaj/mocha.el#69]
I reimplemented imenu support into a new package [js2-imenu-mocha](https://github.com/DamienCassou/js2-imenu-mocha), taking inspiration from your package. I think the code is simpler and also contains more features (e.g., support for `fit()` and `fdescribe()`). I would like to have [this code included into `js2-mode` itself](https://github.com/mooz/js2-mode/issues/575).

**Comment by Alhadis** [comment]
Wouldn't it benefit everybody if this were part of `mocha.el` instead?

**Comment by DamienCassou** [comment]
I think more people would benefit if it was included in js2-mode directly but I'm fine migrating the code to mocha.el if they don't want it. Let's wait a bit for their answer before deciding anything.

**Comment by DamienCassou** [comment]
The work [got merged into js2-mode](https://github.com/mooz/js2-mode/pull/576).
